# still needs libcurl

# opkg
RUN \
	set -x && \
	umask 022 && \
	LC_ALL=POSIX && \
	wget -O /download/opkg-0.3.0.tar.gz \
		http://downloads.yoctoproject.org/releases/opkg/opkg-0.3.0.tar.gz && \
	cd /build && \
	tar xf /download/opkg-0.3.0.tar.gz && \
	cd opkg-0.3.0 && \
	./configure --prefix=/usr
