# openssl
RUN \
	set -xe && \
	curl -ksSL https://www.openssl.org/source/openssl-1.0.2d.tar.gz > \
		/download/openssl-1.0.2d.tar.gz && \
	cd /build && \
	tar xf /download/openssl-1.0.2d.tar.gz && \
	cd openssl-1.0.2d && \
	./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib shared zlib-dynamic && \
	sed -i 's# libcrypto.a##;s# libssl.a##' Makefile && \
	make && \
	mkdir -p /build/openssl-root && \
	make INSTALL_PREFIX=/build/openssl-root install && \
	cd /build/openssl-root && \
	ls -lR > /build/files-openssl.orig && \
	rm -rf /build/openssl-root/etc/ssl/man && \
	rm -rf /build/openssl-root/usr/include && \
	rm -rf /build/openssl-root/usr/lib/pkgconfig && \
	(strip \
		/build/openssl-root/usr/bin/* \
		/build/openssl-root/usr/lib/* \
		/build/openssl-root/usr/inb/*.* || /bin/true) && \
	cd /build/openssl-root && \
	ls -lR > /build/files-openssl && \
	cp -an /build/openssl-root/* /build/root/ && \
        cd /build && \
        rm -rf /build/openssl-1.0.2d /build/openssl-root
	
ADD binutils-bootstrap-assets /build/binutils-bootstrap-assets
RUN \
	set -xe && \
        curl -ksSL http://ftp.gnu.org/gnu/binutils/binutils-2.25.1.tar.bz2 > \
                /download/binutils-2.25.1.tar.bz2 && \
	cd /build && \
	tar xf /download/binutils-2.25.1.tar.bz2 && \
	mkdir binutils-build && \
	cd binutils-build && \
	../binutils-2.25.1/configure \
		--prefix=/usr --disable-nls --disable-werror \
		--with-lib-path=/usr/lib --with-sysroot && \
	MAKE="make -j4" make && \
	mkdir -p /build/deb && \
	cd /build/binutils-build && \
	mkdir -p /build/binutils-root && \
	make DESTDIR=/build/binutils-root install && \
	rm -f /build/binutils-root/usr/bin/strings && \
	rm -f /build/binutils-root/usr/bin/ar && \
	strip /build/binutils-root/usr/bin/* && \
	strip /build/binutils-root/usr/x86_64-unknown-linux-gnu/bin/* && \
	rm -rf /build/binutils-root/usr/share && \
	mkdir -p /build/binutils-deb/control && \
	cd /build/binutils-root && \
	find -type f | xargs md5sum | sed 's/  \.\//  /' > /build/binutils-deb/control/md5sums && \
	cp /build/binutils-bootstrap-assets/control /build/binutils-deb/control/control && \
	cd /build/binutils-deb/control && \
	tar --hard-dereference --portability -zcf ../control.tar.gz . && \
	cd /build/binutils-root && \
	tar --hard-dereference --portability -zcf /build/binutils-deb/data.tar.gz . && \
	cd /build/binutils-deb && \
	echo "2.0" > debian-binary && \
	ar rc /build/deb/binutils-bootstrap_2.25.1-0+uc0_amd64.deb \
		debian-binary control.tar.gz data.tar.gz && \
	rm -rf /build/binutils-bootstrap-assets /build/binutils-2.25.1 /build/binutils-root \
		/build/binutils-deb

# gcc bootstrap

ADD gcc-bootstrap-assets /build/gcc-bootstrap-assets
RUN \
	set -xe && \
	export LC_ALL=POSIX && \
	curl -ksSL http://ftp.gnu.org/gnu/gcc/gcc-5.2.0/gcc-5.2.0.tar.bz2 > \
		/download/gcc-5.2.0.tar.bz2 && \
	curl -ksSL http://www.mpfr.org/mpfr-3.1.3/mpfr-3.1.3.tar.xz > \
		/download/mpfr-3.1.3.tar.xz && \
	curl -ksSL http://ftp.gnu.org/gnu//gmp/gmp-6.0.0a.tar.xz > \
		/download/gmp-6.0.0a.tar.xz && \
	curl -ksSL http://www.multiprecision.org/mpc/download/mpc-1.0.3.tar.gz > \
		/download/mpc-1.0.3.tar.gz && \
	cd /build && \
	tar xf /download/gcc-5.2.0.tar.bz2 && \
	cd gcc-5.2.0 && \
	tar xf /download/mpfr-3.1.3.tar.xz && \
	mv -f mpfr-3.1.3 mpfr && \
	tar xf /download/gmp-6.0.0a.tar.xz && \
	mv -f gmp-6.0.0 gmp && \
	tar xf /download/mpc-1.0.3.tar.gz && \
	mv -f mpc-1.0.3 mpc && \
	bash /build/gcc-bootstrap-assets/fix-paths.sh && \
	mkdir -p ../gcc-build && \
	cd ../gcc-build && \
	../gcc-5.2.0/configure \
		--target=x86_64-uc-linux-gnu --prefix=/usr --with-glibc-version=2.11 \
		--with-sysroot=/ --with-newlib --without-headers --with-local-prefix=/ \
		--with-native-system-header-dir=/usr/include --disable-nls --disable-shared \
		--disable-multilib --disable-decimal-float --disable-threads \
		--disable-libatomic --disable-libgomp --disable-libquadmath --disable-libssp \
		--disable-libquadmath --disable-libssp --disable-libvtv --disable-libstdcxx \
		--enable-languages=c,c++ && \
	MAKE="make -j4" make && \
	mkdir -p /build/gcc-root && \
	make DESTDIR=/build/gcc-root make install

CMD ["/bin/bash"]	
	
